### ISSUE TITLE
Version in `./internal/version/version.go` shows 1.0.4  (for the 1.0.5 tag / master)

### ISSUE THREAD

**Issue by bwalding** [sqreen/go-agent#178]
The version located in  [internal/version/version.go](https://github.com/sqreen/go-agent/blob/master/internal/version/version.go) is 1.0.4 - but the repo is tagged at 1.0.5

This makes it a bit confusing when you build the instrumentation agent and it says 1.0.4 even though you're pulling down the 1.0.5 tagged code.

**Comment by Julio-Guerra** [comment]
I just release v1.0.6 to fix this problem.
Note also that you should start migrating to https://github.com/DataDog/dd-trace-go
Let me know if you need advices or help.
