### ISSUE TITLE
Jenkinsfile Update

### ISSUE THREAD

**Issue by omegas27** [sqreen/go-agent#20]
I checked the Jenkinsfile and i was wondering, why you do not just use containers with the dependencies you need in different steps ?

You could have a container with make, one with go, one with codecov and run it instead of building your own image no ?

You can keep yours for local dev still :)

You don't have to use only one container for your build :)

You would write it like so : 
! This is not valid syntax, it's just to explain the idea

podTemplate(containers: [go, make, codecov]) {
      stage('Tests') {
                    parallel([
                        'Regular': {
                            container('go') {
                                sh 'go env'
                              
                           }
                           container('make') { 
                                 sh 'make test'
                            }
                        },
                        'With coverage': {
                             container('make') { 
                                sh 'make test-coverage'
                            }
                            container('codevov') { 
                                codecov.analyze('codecov-agent-go-token')
                            }
                        },
                        'With race detection': {
                            container('make') { 
                                 sh 'make test-race'
                            }
                        }
                    ])
}

**Comment by Julio-Guerra** [comment]
Good point. But indeed, I tend to always rely on make to run commands, and it's rarely included in docker images so I sadly rebuild them :disappointed: to at least add it.

**Comment by Julio-Guerra** [comment]
Simplified now using docker's golang images, which do have make. Nothing else is required so far.
