### ISSUE TITLE
Release date about build-in security response?

### ISSUE THREAD

**Issue by alanchchen** [sqreen/go-agent#33]
Built-in security responses to protect user accounts is not supported yet.
Any roadmap about this?  Thanks

**Comment by Julio-Guerra** [comment]
Hello @alanchchen 
The next Pull Requests will only be about security responses. They will add the support for blocking users or IP addresses. Redirection support will be added later as they require more advanced backend communication we don't have yet.

**Comment by Julio-Guerra** [comment]
FYI, the release date is now set to April 12, 2019 with [v0.1.0-beta.4](https://github.com/sqreen/go-agent/milestone/7)

**Comment by Julio-Guerra** [comment]
@alanchchen You can now block IP addresses and users using our Playbooks :-)
Let me know if you need any help.
